name: PlayerCompass1_12_2
version: ${project.version}
main: net.kunmc.lab.playercompass1_12_2.PlayerCompassPlugin
depend: [ ProtocolLib ]
commands:
  changeupdateperiod:
    usage: /changeupdateperiod <period>
    permission: playercompass.changeupdateperiod
  compass:
    usage: /compass <player>
    permission: playercompass.compass
  playerpos:
    usage: /playerpos <player>
    permission: playercompass.playerpos
  playerposoff:
    usage: /playerposoff
    permission: playercompass.playerpos
  kun:
    usage: /kun
    permission: playercompass.kun
  kunxyz:
    usage: /kunxyz
    permission: playercompass.kunxyz

permissions:
  playercompass.compass:
    default: op
  playercompass.playerpos:
    default: op
  playercompass.changeupdateperiod:
    default: op
  playercompass.kun:
    default: op
  playercompass.kunxyz:
    default: op